#include <stdint.h>
#include "movements.h"

float movements_standby_pose[8] = {
	MOV_SRV_ST_V, MOV_SRV_ST_H, MOV_SRV_ST_H, MOV_SRV_ST_V, MOV_SRV_ST_V, MOV_SRV_ST_H, MOV_SRV_ST_H, MOV_SRV_ST_V
};
float movements_calibration_pose[8] = {
	MOV_SRV_CA_V, MOV_SRV_CA_H, MOV_SRV_CA_H, MOV_SRV_CA_V, MOV_SRV_CA_V, MOV_SRV_CA_H, MOV_SRV_CA_H, MOV_SRV_CA_V
};

float movements_buttons_mode_patterns[576] = {
	//Forward
	MOV_BTNS_MODE_FW_BW_SP1_V_DW, MOV_BTNS_MODE_FW_BW_SP1_H_BW, MOV_BTNS_MODE_FW_BW_SP1_H_BW, MOV_BTNS_MODE_FW_BW_SP1_V_DW, MOV_BTNS_MODE_FW_BW_SP1_V_DW, MOV_BTNS_MODE_FW_BW_SP1_H_FW, MOV_BTNS_MODE_FW_BW_SP1_H_FW, MOV_BTNS_MODE_FW_BW_SP1_V_DW,
	MOV_BTNS_MODE_FW_BW_SP1_V_UP, MOV_BTNS_MODE_FW_BW_SP1_H_FW, MOV_BTNS_MODE_FW_BW_SP1_H_FW, MOV_BTNS_MODE_FW_BW_SP1_V_DW, MOV_BTNS_MODE_FW_BW_SP1_V_UP, MOV_BTNS_MODE_FW_BW_SP1_H_BW, MOV_BTNS_MODE_FW_BW_SP1_H_BW, MOV_BTNS_MODE_FW_BW_SP1_V_DW,
	MOV_BTNS_MODE_FW_BW_SP1_V_DW, MOV_BTNS_MODE_FW_BW_SP1_H_FW, MOV_BTNS_MODE_FW_BW_SP1_H_FW, MOV_BTNS_MODE_FW_BW_SP1_V_DW, MOV_BTNS_MODE_FW_BW_SP1_V_DW, MOV_BTNS_MODE_FW_BW_SP1_H_BW, MOV_BTNS_MODE_FW_BW_SP1_H_BW, MOV_BTNS_MODE_FW_BW_SP1_V_DW,
	MOV_BTNS_MODE_FW_BW_SP1_V_DW, MOV_BTNS_MODE_FW_BW_SP1_H_BW, MOV_BTNS_MODE_FW_BW_SP1_H_BW, MOV_BTNS_MODE_FW_BW_SP1_V_UP, MOV_BTNS_MODE_FW_BW_SP1_V_DW, MOV_BTNS_MODE_FW_BW_SP1_H_FW, MOV_BTNS_MODE_FW_BW_SP1_H_FW, MOV_BTNS_MODE_FW_BW_SP1_V_UP,

	MOV_BTNS_MODE_FW_BW_SP2_V_DW, MOV_BTNS_MODE_FW_BW_SP2_H_BW, MOV_BTNS_MODE_FW_BW_SP2_H_BW, MOV_BTNS_MODE_FW_BW_SP2_V_DW, MOV_BTNS_MODE_FW_BW_SP2_V_DW, MOV_BTNS_MODE_FW_BW_SP2_H_FW, MOV_BTNS_MODE_FW_BW_SP2_H_FW, MOV_BTNS_MODE_FW_BW_SP2_V_DW,
	MOV_BTNS_MODE_FW_BW_SP2_V_UP, MOV_BTNS_MODE_FW_BW_SP2_H_FW, MOV_BTNS_MODE_FW_BW_SP2_H_FW, MOV_BTNS_MODE_FW_BW_SP2_V_DW, MOV_BTNS_MODE_FW_BW_SP2_V_UP, MOV_BTNS_MODE_FW_BW_SP2_H_BW, MOV_BTNS_MODE_FW_BW_SP2_H_BW, MOV_BTNS_MODE_FW_BW_SP2_V_DW,
	MOV_BTNS_MODE_FW_BW_SP2_V_DW, MOV_BTNS_MODE_FW_BW_SP2_H_FW, MOV_BTNS_MODE_FW_BW_SP2_H_FW, MOV_BTNS_MODE_FW_BW_SP2_V_DW, MOV_BTNS_MODE_FW_BW_SP2_V_DW, MOV_BTNS_MODE_FW_BW_SP2_H_BW, MOV_BTNS_MODE_FW_BW_SP2_H_BW, MOV_BTNS_MODE_FW_BW_SP2_V_DW,
	MOV_BTNS_MODE_FW_BW_SP2_V_DW, MOV_BTNS_MODE_FW_BW_SP2_H_BW, MOV_BTNS_MODE_FW_BW_SP2_H_BW, MOV_BTNS_MODE_FW_BW_SP2_V_UP, MOV_BTNS_MODE_FW_BW_SP2_V_DW, MOV_BTNS_MODE_FW_BW_SP2_H_FW, MOV_BTNS_MODE_FW_BW_SP2_H_FW, MOV_BTNS_MODE_FW_BW_SP2_V_UP,

	MOV_BTNS_MODE_FW_BW_SP3_V_DW, MOV_BTNS_MODE_FW_BW_SP3_H_BW, MOV_BTNS_MODE_FW_BW_SP3_H_BW, MOV_BTNS_MODE_FW_BW_SP3_V_DW, MOV_BTNS_MODE_FW_BW_SP3_V_DW, MOV_BTNS_MODE_FW_BW_SP3_H_FW, MOV_BTNS_MODE_FW_BW_SP3_H_FW, MOV_BTNS_MODE_FW_BW_SP3_V_DW,
	MOV_BTNS_MODE_FW_BW_SP3_V_UP, MOV_BTNS_MODE_FW_BW_SP3_H_FW, MOV_BTNS_MODE_FW_BW_SP3_H_FW, MOV_BTNS_MODE_FW_BW_SP3_V_DW, MOV_BTNS_MODE_FW_BW_SP3_V_UP, MOV_BTNS_MODE_FW_BW_SP3_H_BW, MOV_BTNS_MODE_FW_BW_SP3_H_BW, MOV_BTNS_MODE_FW_BW_SP3_V_DW,
	MOV_BTNS_MODE_FW_BW_SP3_V_DW, MOV_BTNS_MODE_FW_BW_SP3_H_FW, MOV_BTNS_MODE_FW_BW_SP3_H_FW, MOV_BTNS_MODE_FW_BW_SP3_V_DW, MOV_BTNS_MODE_FW_BW_SP3_V_DW, MOV_BTNS_MODE_FW_BW_SP3_H_BW, MOV_BTNS_MODE_FW_BW_SP3_H_BW, MOV_BTNS_MODE_FW_BW_SP3_V_DW,
	MOV_BTNS_MODE_FW_BW_SP3_V_DW, MOV_BTNS_MODE_FW_BW_SP3_H_BW, MOV_BTNS_MODE_FW_BW_SP3_H_BW, MOV_BTNS_MODE_FW_BW_SP3_V_UP, MOV_BTNS_MODE_FW_BW_SP3_V_DW, MOV_BTNS_MODE_FW_BW_SP3_H_FW, MOV_BTNS_MODE_FW_BW_SP3_H_FW, MOV_BTNS_MODE_FW_BW_SP3_V_UP,

	//Backward
	MOV_BTNS_MODE_FW_BW_SP1_V_DW, MOV_BTNS_MODE_FW_BW_SP1_H_BW, MOV_BTNS_MODE_FW_BW_SP1_H_BW, MOV_BTNS_MODE_FW_BW_SP1_V_DW, MOV_BTNS_MODE_FW_BW_SP1_V_DW, MOV_BTNS_MODE_FW_BW_SP1_H_FW, MOV_BTNS_MODE_FW_BW_SP1_H_FW, MOV_BTNS_MODE_FW_BW_SP1_V_DW,
	MOV_BTNS_MODE_FW_BW_SP1_V_DW, MOV_BTNS_MODE_FW_BW_SP1_H_FW, MOV_BTNS_MODE_FW_BW_SP1_H_FW, MOV_BTNS_MODE_FW_BW_SP1_V_UP, MOV_BTNS_MODE_FW_BW_SP1_V_DW, MOV_BTNS_MODE_FW_BW_SP1_H_BW, MOV_BTNS_MODE_FW_BW_SP1_H_BW, MOV_BTNS_MODE_FW_BW_SP1_V_UP,
	MOV_BTNS_MODE_FW_BW_SP1_V_DW, MOV_BTNS_MODE_FW_BW_SP1_H_FW, MOV_BTNS_MODE_FW_BW_SP1_H_FW, MOV_BTNS_MODE_FW_BW_SP1_V_DW, MOV_BTNS_MODE_FW_BW_SP1_V_DW, MOV_BTNS_MODE_FW_BW_SP1_H_BW, MOV_BTNS_MODE_FW_BW_SP1_H_BW, MOV_BTNS_MODE_FW_BW_SP1_V_DW,
	MOV_BTNS_MODE_FW_BW_SP1_V_UP, MOV_BTNS_MODE_FW_BW_SP1_H_BW, MOV_BTNS_MODE_FW_BW_SP1_H_BW, MOV_BTNS_MODE_FW_BW_SP1_V_DW, MOV_BTNS_MODE_FW_BW_SP1_V_UP, MOV_BTNS_MODE_FW_BW_SP1_H_FW, MOV_BTNS_MODE_FW_BW_SP1_H_FW, MOV_BTNS_MODE_FW_BW_SP1_V_DW,

	MOV_BTNS_MODE_FW_BW_SP2_V_DW, MOV_BTNS_MODE_FW_BW_SP2_H_BW, MOV_BTNS_MODE_FW_BW_SP2_H_BW, MOV_BTNS_MODE_FW_BW_SP2_V_DW, MOV_BTNS_MODE_FW_BW_SP2_V_DW, MOV_BTNS_MODE_FW_BW_SP2_H_FW, MOV_BTNS_MODE_FW_BW_SP2_H_FW, MOV_BTNS_MODE_FW_BW_SP2_V_DW,
	MOV_BTNS_MODE_FW_BW_SP2_V_DW, MOV_BTNS_MODE_FW_BW_SP2_H_FW, MOV_BTNS_MODE_FW_BW_SP2_H_FW, MOV_BTNS_MODE_FW_BW_SP2_V_UP, MOV_BTNS_MODE_FW_BW_SP2_V_DW, MOV_BTNS_MODE_FW_BW_SP2_H_BW, MOV_BTNS_MODE_FW_BW_SP2_H_BW, MOV_BTNS_MODE_FW_BW_SP2_V_UP,
	MOV_BTNS_MODE_FW_BW_SP2_V_DW, MOV_BTNS_MODE_FW_BW_SP2_H_FW, MOV_BTNS_MODE_FW_BW_SP2_H_FW, MOV_BTNS_MODE_FW_BW_SP2_V_DW, MOV_BTNS_MODE_FW_BW_SP2_V_DW, MOV_BTNS_MODE_FW_BW_SP2_H_BW, MOV_BTNS_MODE_FW_BW_SP2_H_BW, MOV_BTNS_MODE_FW_BW_SP2_V_DW,
	MOV_BTNS_MODE_FW_BW_SP2_V_UP, MOV_BTNS_MODE_FW_BW_SP2_H_BW, MOV_BTNS_MODE_FW_BW_SP2_H_BW, MOV_BTNS_MODE_FW_BW_SP2_V_DW, MOV_BTNS_MODE_FW_BW_SP2_V_UP, MOV_BTNS_MODE_FW_BW_SP2_H_FW, MOV_BTNS_MODE_FW_BW_SP2_H_FW, MOV_BTNS_MODE_FW_BW_SP2_V_DW,

	MOV_BTNS_MODE_FW_BW_SP3_V_DW, MOV_BTNS_MODE_FW_BW_SP3_H_BW, MOV_BTNS_MODE_FW_BW_SP3_H_BW, MOV_BTNS_MODE_FW_BW_SP3_V_DW, MOV_BTNS_MODE_FW_BW_SP3_V_DW, MOV_BTNS_MODE_FW_BW_SP3_H_FW, MOV_BTNS_MODE_FW_BW_SP3_H_FW, MOV_BTNS_MODE_FW_BW_SP3_V_DW,
	MOV_BTNS_MODE_FW_BW_SP3_V_DW, MOV_BTNS_MODE_FW_BW_SP3_H_FW, MOV_BTNS_MODE_FW_BW_SP3_H_FW, MOV_BTNS_MODE_FW_BW_SP3_V_UP, MOV_BTNS_MODE_FW_BW_SP3_V_DW, MOV_BTNS_MODE_FW_BW_SP3_H_BW, MOV_BTNS_MODE_FW_BW_SP3_H_BW, MOV_BTNS_MODE_FW_BW_SP3_V_UP,
	MOV_BTNS_MODE_FW_BW_SP3_V_DW, MOV_BTNS_MODE_FW_BW_SP3_H_FW, MOV_BTNS_MODE_FW_BW_SP3_H_FW, MOV_BTNS_MODE_FW_BW_SP3_V_DW, MOV_BTNS_MODE_FW_BW_SP3_V_DW, MOV_BTNS_MODE_FW_BW_SP3_H_BW, MOV_BTNS_MODE_FW_BW_SP3_H_BW, MOV_BTNS_MODE_FW_BW_SP3_V_DW,
	MOV_BTNS_MODE_FW_BW_SP3_V_UP, MOV_BTNS_MODE_FW_BW_SP3_H_BW, MOV_BTNS_MODE_FW_BW_SP3_H_BW, MOV_BTNS_MODE_FW_BW_SP3_V_DW, MOV_BTNS_MODE_FW_BW_SP3_V_UP, MOV_BTNS_MODE_FW_BW_SP3_H_FW, MOV_BTNS_MODE_FW_BW_SP3_H_FW, MOV_BTNS_MODE_FW_BW_SP3_V_DW,

	//Turn Right
	MOV_BTNS_MODE_TR_TL_SP1_V_DW, MOV_BTNS_MODE_TR_TL_SP1_H_FW, MOV_BTNS_MODE_TR_TL_SP1_H_FW, MOV_BTNS_MODE_TR_TL_SP1_V_DW, MOV_BTNS_MODE_TR_TL_SP1_V_DW, MOV_BTNS_MODE_TR_TL_SP1_H_FW, MOV_BTNS_MODE_TR_TL_SP1_H_FW, MOV_BTNS_MODE_TR_TL_SP1_V_DW,
	MOV_BTNS_MODE_TR_TL_SP1_V_DW, MOV_BTNS_MODE_TR_TL_SP1_H_BW, MOV_BTNS_MODE_TR_TL_SP1_H_BW, MOV_BTNS_MODE_TR_TL_SP1_V_UP, MOV_BTNS_MODE_TR_TL_SP1_V_DW, MOV_BTNS_MODE_TR_TL_SP1_H_BW, MOV_BTNS_MODE_TR_TL_SP1_H_BW, MOV_BTNS_MODE_TR_TL_SP1_V_UP,
	MOV_BTNS_MODE_TR_TL_SP1_V_DW, MOV_BTNS_MODE_TR_TL_SP1_H_BW, MOV_BTNS_MODE_TR_TL_SP1_H_BW, MOV_BTNS_MODE_TR_TL_SP1_V_DW, MOV_BTNS_MODE_TR_TL_SP1_V_DW, MOV_BTNS_MODE_TR_TL_SP1_H_BW, MOV_BTNS_MODE_TR_TL_SP1_H_BW, MOV_BTNS_MODE_TR_TL_SP1_V_DW,
	MOV_BTNS_MODE_TR_TL_SP1_V_UP, MOV_BTNS_MODE_TR_TL_SP1_H_FW, MOV_BTNS_MODE_TR_TL_SP1_H_FW, MOV_BTNS_MODE_TR_TL_SP1_V_DW, MOV_BTNS_MODE_TR_TL_SP1_V_UP, MOV_BTNS_MODE_TR_TL_SP1_H_FW, MOV_BTNS_MODE_TR_TL_SP1_H_FW, MOV_BTNS_MODE_TR_TL_SP1_V_DW,

	MOV_BTNS_MODE_TR_TL_SP2_V_DW, MOV_BTNS_MODE_TR_TL_SP2_H_FW, MOV_BTNS_MODE_TR_TL_SP2_H_FW, MOV_BTNS_MODE_TR_TL_SP2_V_DW, MOV_BTNS_MODE_TR_TL_SP2_V_DW, MOV_BTNS_MODE_TR_TL_SP2_H_FW, MOV_BTNS_MODE_TR_TL_SP2_H_FW, MOV_BTNS_MODE_TR_TL_SP2_V_DW,
	MOV_BTNS_MODE_TR_TL_SP2_V_DW, MOV_BTNS_MODE_TR_TL_SP2_H_BW, MOV_BTNS_MODE_TR_TL_SP2_H_BW, MOV_BTNS_MODE_TR_TL_SP2_V_UP, MOV_BTNS_MODE_TR_TL_SP2_V_DW, MOV_BTNS_MODE_TR_TL_SP2_H_BW, MOV_BTNS_MODE_TR_TL_SP2_H_BW, MOV_BTNS_MODE_TR_TL_SP2_V_UP,
	MOV_BTNS_MODE_TR_TL_SP2_V_DW, MOV_BTNS_MODE_TR_TL_SP2_H_BW, MOV_BTNS_MODE_TR_TL_SP2_H_BW, MOV_BTNS_MODE_TR_TL_SP2_V_DW, MOV_BTNS_MODE_TR_TL_SP2_V_DW, MOV_BTNS_MODE_TR_TL_SP2_H_BW, MOV_BTNS_MODE_TR_TL_SP2_H_BW, MOV_BTNS_MODE_TR_TL_SP2_V_DW,
	MOV_BTNS_MODE_TR_TL_SP2_V_UP, MOV_BTNS_MODE_TR_TL_SP2_H_FW, MOV_BTNS_MODE_TR_TL_SP2_H_FW, MOV_BTNS_MODE_TR_TL_SP2_V_DW, MOV_BTNS_MODE_TR_TL_SP2_V_UP, MOV_BTNS_MODE_TR_TL_SP2_H_FW, MOV_BTNS_MODE_TR_TL_SP2_H_FW, MOV_BTNS_MODE_TR_TL_SP2_V_DW,

	MOV_BTNS_MODE_TR_TL_SP3_V_DW, MOV_BTNS_MODE_TR_TL_SP3_H_FW, MOV_BTNS_MODE_TR_TL_SP3_H_FW, MOV_BTNS_MODE_TR_TL_SP3_V_DW, MOV_BTNS_MODE_TR_TL_SP3_V_DW, MOV_BTNS_MODE_TR_TL_SP3_H_FW, MOV_BTNS_MODE_TR_TL_SP3_H_FW, MOV_BTNS_MODE_TR_TL_SP3_V_DW,
	MOV_BTNS_MODE_TR_TL_SP3_V_DW, MOV_BTNS_MODE_TR_TL_SP3_H_BW, MOV_BTNS_MODE_TR_TL_SP3_H_BW, MOV_BTNS_MODE_TR_TL_SP3_V_UP, MOV_BTNS_MODE_TR_TL_SP3_V_DW, MOV_BTNS_MODE_TR_TL_SP3_H_BW, MOV_BTNS_MODE_TR_TL_SP3_H_BW, MOV_BTNS_MODE_TR_TL_SP3_V_UP,
	MOV_BTNS_MODE_TR_TL_SP3_V_DW, MOV_BTNS_MODE_TR_TL_SP3_H_BW, MOV_BTNS_MODE_TR_TL_SP3_H_BW, MOV_BTNS_MODE_TR_TL_SP3_V_DW, MOV_BTNS_MODE_TR_TL_SP3_V_DW, MOV_BTNS_MODE_TR_TL_SP3_H_BW, MOV_BTNS_MODE_TR_TL_SP3_H_BW, MOV_BTNS_MODE_TR_TL_SP3_V_DW,
	MOV_BTNS_MODE_TR_TL_SP3_V_UP, MOV_BTNS_MODE_TR_TL_SP3_H_FW, MOV_BTNS_MODE_TR_TL_SP3_H_FW, MOV_BTNS_MODE_TR_TL_SP3_V_DW, MOV_BTNS_MODE_TR_TL_SP3_V_UP, MOV_BTNS_MODE_TR_TL_SP3_H_FW, MOV_BTNS_MODE_TR_TL_SP3_H_FW, MOV_BTNS_MODE_TR_TL_SP3_V_DW,

	//Turn Left
	MOV_BTNS_MODE_TR_TL_SP1_V_DW, MOV_BTNS_MODE_TR_TL_SP1_H_FW, MOV_BTNS_MODE_TR_TL_SP1_H_FW, MOV_BTNS_MODE_TR_TL_SP1_V_DW, MOV_BTNS_MODE_TR_TL_SP1_V_DW, MOV_BTNS_MODE_TR_TL_SP1_H_FW, MOV_BTNS_MODE_TR_TL_SP1_H_FW, MOV_BTNS_MODE_TR_TL_SP1_V_DW,
	MOV_BTNS_MODE_TR_TL_SP1_V_UP, MOV_BTNS_MODE_TR_TL_SP1_H_BW, MOV_BTNS_MODE_TR_TL_SP1_H_BW, MOV_BTNS_MODE_TR_TL_SP1_V_DW, MOV_BTNS_MODE_TR_TL_SP1_V_UP, MOV_BTNS_MODE_TR_TL_SP1_H_BW, MOV_BTNS_MODE_TR_TL_SP1_H_BW, MOV_BTNS_MODE_TR_TL_SP1_V_DW,
	MOV_BTNS_MODE_TR_TL_SP1_V_DW, MOV_BTNS_MODE_TR_TL_SP1_H_BW, MOV_BTNS_MODE_TR_TL_SP1_H_BW, MOV_BTNS_MODE_TR_TL_SP1_V_DW, MOV_BTNS_MODE_TR_TL_SP1_V_DW, MOV_BTNS_MODE_TR_TL_SP1_H_BW, MOV_BTNS_MODE_TR_TL_SP1_H_BW, MOV_BTNS_MODE_TR_TL_SP1_V_DW,
	MOV_BTNS_MODE_TR_TL_SP1_V_DW, MOV_BTNS_MODE_TR_TL_SP1_H_FW, MOV_BTNS_MODE_TR_TL_SP1_H_FW, MOV_BTNS_MODE_TR_TL_SP1_V_UP, MOV_BTNS_MODE_TR_TL_SP1_V_DW, MOV_BTNS_MODE_TR_TL_SP1_H_FW, MOV_BTNS_MODE_TR_TL_SP1_H_FW, MOV_BTNS_MODE_TR_TL_SP1_V_UP,

	MOV_BTNS_MODE_TR_TL_SP2_V_DW, MOV_BTNS_MODE_TR_TL_SP2_H_FW, MOV_BTNS_MODE_TR_TL_SP2_H_FW, MOV_BTNS_MODE_TR_TL_SP2_V_DW, MOV_BTNS_MODE_TR_TL_SP2_V_DW, MOV_BTNS_MODE_TR_TL_SP2_H_FW, MOV_BTNS_MODE_TR_TL_SP2_H_FW, MOV_BTNS_MODE_TR_TL_SP2_V_DW,
	MOV_BTNS_MODE_TR_TL_SP2_V_UP, MOV_BTNS_MODE_TR_TL_SP2_H_BW, MOV_BTNS_MODE_TR_TL_SP2_H_BW, MOV_BTNS_MODE_TR_TL_SP2_V_DW, MOV_BTNS_MODE_TR_TL_SP2_V_UP, MOV_BTNS_MODE_TR_TL_SP2_H_BW, MOV_BTNS_MODE_TR_TL_SP2_H_BW, MOV_BTNS_MODE_TR_TL_SP2_V_DW,
	MOV_BTNS_MODE_TR_TL_SP2_V_DW, MOV_BTNS_MODE_TR_TL_SP2_H_BW, MOV_BTNS_MODE_TR_TL_SP2_H_BW, MOV_BTNS_MODE_TR_TL_SP2_V_DW, MOV_BTNS_MODE_TR_TL_SP2_V_DW, MOV_BTNS_MODE_TR_TL_SP2_H_BW, MOV_BTNS_MODE_TR_TL_SP2_H_BW, MOV_BTNS_MODE_TR_TL_SP2_V_DW,
	MOV_BTNS_MODE_TR_TL_SP2_V_DW, MOV_BTNS_MODE_TR_TL_SP2_H_FW, MOV_BTNS_MODE_TR_TL_SP2_H_FW, MOV_BTNS_MODE_TR_TL_SP2_V_UP, MOV_BTNS_MODE_TR_TL_SP2_V_DW, MOV_BTNS_MODE_TR_TL_SP2_H_FW, MOV_BTNS_MODE_TR_TL_SP2_H_FW, MOV_BTNS_MODE_TR_TL_SP2_V_UP,

	MOV_BTNS_MODE_TR_TL_SP3_V_DW, MOV_BTNS_MODE_TR_TL_SP3_H_FW, MOV_BTNS_MODE_TR_TL_SP3_H_FW, MOV_BTNS_MODE_TR_TL_SP3_V_DW, MOV_BTNS_MODE_TR_TL_SP3_V_DW, MOV_BTNS_MODE_TR_TL_SP3_H_FW, MOV_BTNS_MODE_TR_TL_SP3_H_FW, MOV_BTNS_MODE_TR_TL_SP3_V_DW,
	MOV_BTNS_MODE_TR_TL_SP3_V_UP, MOV_BTNS_MODE_TR_TL_SP3_H_BW, MOV_BTNS_MODE_TR_TL_SP3_H_BW, MOV_BTNS_MODE_TR_TL_SP3_V_DW, MOV_BTNS_MODE_TR_TL_SP3_V_UP, MOV_BTNS_MODE_TR_TL_SP3_H_BW, MOV_BTNS_MODE_TR_TL_SP3_H_BW, MOV_BTNS_MODE_TR_TL_SP3_V_DW,
	MOV_BTNS_MODE_TR_TL_SP3_V_DW, MOV_BTNS_MODE_TR_TL_SP3_H_BW, MOV_BTNS_MODE_TR_TL_SP3_H_BW, MOV_BTNS_MODE_TR_TL_SP3_V_DW, MOV_BTNS_MODE_TR_TL_SP3_V_DW, MOV_BTNS_MODE_TR_TL_SP3_H_BW, MOV_BTNS_MODE_TR_TL_SP3_H_BW, MOV_BTNS_MODE_TR_TL_SP3_V_DW,
	MOV_BTNS_MODE_TR_TL_SP3_V_DW, MOV_BTNS_MODE_TR_TL_SP3_H_FW, MOV_BTNS_MODE_TR_TL_SP3_H_FW, MOV_BTNS_MODE_TR_TL_SP3_V_UP, MOV_BTNS_MODE_TR_TL_SP3_V_DW, MOV_BTNS_MODE_TR_TL_SP3_H_FW, MOV_BTNS_MODE_TR_TL_SP3_H_FW, MOV_BTNS_MODE_TR_TL_SP3_V_UP,

	//Slide Left
	MOV_BTNS_MODE_SR_SL_SP1_V_DW, MOV_BTNS_MODE_SR_SL_SP1_H_BW, MOV_BTNS_MODE_SR_SL_SP1_H_FW, MOV_BTNS_MODE_SR_SL_SP1_V_DW, MOV_BTNS_MODE_SR_SL_SP1_V_DW, MOV_BTNS_MODE_SR_SL_SP1_H_FW, MOV_BTNS_MODE_SR_SL_SP1_H_BW, MOV_BTNS_MODE_SR_SL_SP1_V_DW,
	MOV_BTNS_MODE_SR_SL_SP1_V_DW, MOV_BTNS_MODE_SR_SL_SP1_H_FW, MOV_BTNS_MODE_SR_SL_SP1_H_BW, MOV_BTNS_MODE_SR_SL_SP1_V_UP, MOV_BTNS_MODE_SR_SL_SP1_V_DW, MOV_BTNS_MODE_SR_SL_SP1_H_BW, MOV_BTNS_MODE_SR_SL_SP1_H_FW, MOV_BTNS_MODE_SR_SL_SP1_V_UP,
	MOV_BTNS_MODE_SR_SL_SP1_V_DW, MOV_BTNS_MODE_SR_SL_SP1_H_FW, MOV_BTNS_MODE_SR_SL_SP1_H_BW, MOV_BTNS_MODE_SR_SL_SP1_V_DW, MOV_BTNS_MODE_SR_SL_SP1_V_DW, MOV_BTNS_MODE_SR_SL_SP1_H_BW, MOV_BTNS_MODE_SR_SL_SP1_H_FW, MOV_BTNS_MODE_SR_SL_SP1_V_DW,
	MOV_BTNS_MODE_SR_SL_SP1_V_UP, MOV_BTNS_MODE_SR_SL_SP1_H_BW, MOV_BTNS_MODE_SR_SL_SP1_H_FW, MOV_BTNS_MODE_SR_SL_SP1_V_DW, MOV_BTNS_MODE_SR_SL_SP1_V_UP, MOV_BTNS_MODE_SR_SL_SP1_H_FW, MOV_BTNS_MODE_SR_SL_SP1_H_BW, MOV_BTNS_MODE_SR_SL_SP1_V_DW,

	MOV_BTNS_MODE_SR_SL_SP2_V_DW, MOV_BTNS_MODE_SR_SL_SP2_H_BW, MOV_BTNS_MODE_SR_SL_SP2_H_FW, MOV_BTNS_MODE_SR_SL_SP2_V_DW, MOV_BTNS_MODE_SR_SL_SP2_V_DW, MOV_BTNS_MODE_SR_SL_SP2_H_FW, MOV_BTNS_MODE_SR_SL_SP2_H_BW, MOV_BTNS_MODE_SR_SL_SP2_V_DW,
	MOV_BTNS_MODE_SR_SL_SP2_V_DW, MOV_BTNS_MODE_SR_SL_SP2_H_FW, MOV_BTNS_MODE_SR_SL_SP2_H_BW, MOV_BTNS_MODE_SR_SL_SP2_V_UP, MOV_BTNS_MODE_SR_SL_SP2_V_DW, MOV_BTNS_MODE_SR_SL_SP2_H_BW, MOV_BTNS_MODE_SR_SL_SP2_H_FW, MOV_BTNS_MODE_SR_SL_SP2_V_UP,
	MOV_BTNS_MODE_SR_SL_SP2_V_DW, MOV_BTNS_MODE_SR_SL_SP2_H_FW, MOV_BTNS_MODE_SR_SL_SP2_H_BW, MOV_BTNS_MODE_SR_SL_SP2_V_DW, MOV_BTNS_MODE_SR_SL_SP2_V_DW, MOV_BTNS_MODE_SR_SL_SP2_H_BW, MOV_BTNS_MODE_SR_SL_SP2_H_FW, MOV_BTNS_MODE_SR_SL_SP2_V_DW,
	MOV_BTNS_MODE_SR_SL_SP2_V_UP, MOV_BTNS_MODE_SR_SL_SP2_H_BW, MOV_BTNS_MODE_SR_SL_SP2_H_FW, MOV_BTNS_MODE_SR_SL_SP2_V_DW, MOV_BTNS_MODE_SR_SL_SP2_V_UP, MOV_BTNS_MODE_SR_SL_SP2_H_FW, MOV_BTNS_MODE_SR_SL_SP2_H_BW, MOV_BTNS_MODE_SR_SL_SP2_V_DW,

	MOV_BTNS_MODE_SR_SL_SP3_V_DW, MOV_BTNS_MODE_SR_SL_SP3_H_BW, MOV_BTNS_MODE_SR_SL_SP3_H_FW, MOV_BTNS_MODE_SR_SL_SP3_V_DW, MOV_BTNS_MODE_SR_SL_SP3_V_DW, MOV_BTNS_MODE_SR_SL_SP3_H_FW, MOV_BTNS_MODE_SR_SL_SP3_H_BW, MOV_BTNS_MODE_SR_SL_SP3_V_DW,
	MOV_BTNS_MODE_SR_SL_SP3_V_DW, MOV_BTNS_MODE_SR_SL_SP3_H_FW, MOV_BTNS_MODE_SR_SL_SP3_H_BW, MOV_BTNS_MODE_SR_SL_SP3_V_UP, MOV_BTNS_MODE_SR_SL_SP3_V_DW, MOV_BTNS_MODE_SR_SL_SP3_H_BW, MOV_BTNS_MODE_SR_SL_SP3_H_FW, MOV_BTNS_MODE_SR_SL_SP3_V_UP,
	MOV_BTNS_MODE_SR_SL_SP3_V_DW, MOV_BTNS_MODE_SR_SL_SP3_H_FW, MOV_BTNS_MODE_SR_SL_SP3_H_BW, MOV_BTNS_MODE_SR_SL_SP3_V_DW, MOV_BTNS_MODE_SR_SL_SP3_V_DW, MOV_BTNS_MODE_SR_SL_SP3_H_BW, MOV_BTNS_MODE_SR_SL_SP3_H_FW, MOV_BTNS_MODE_SR_SL_SP3_V_DW,
	MOV_BTNS_MODE_SR_SL_SP3_V_UP, MOV_BTNS_MODE_SR_SL_SP3_H_BW, MOV_BTNS_MODE_SR_SL_SP3_H_FW, MOV_BTNS_MODE_SR_SL_SP3_V_DW, MOV_BTNS_MODE_SR_SL_SP3_V_UP, MOV_BTNS_MODE_SR_SL_SP3_H_FW, MOV_BTNS_MODE_SR_SL_SP3_H_BW, MOV_BTNS_MODE_SR_SL_SP3_V_DW,

	//Slide Right
	MOV_BTNS_MODE_SR_SL_SP1_V_DW, MOV_BTNS_MODE_SR_SL_SP1_H_BW, MOV_BTNS_MODE_SR_SL_SP1_H_FW, MOV_BTNS_MODE_SR_SL_SP1_V_DW, MOV_BTNS_MODE_SR_SL_SP1_V_DW, MOV_BTNS_MODE_SR_SL_SP1_H_FW, MOV_BTNS_MODE_SR_SL_SP1_H_BW, MOV_BTNS_MODE_SR_SL_SP1_V_DW,
	MOV_BTNS_MODE_SR_SL_SP1_V_UP, MOV_BTNS_MODE_SR_SL_SP1_H_FW, MOV_BTNS_MODE_SR_SL_SP1_H_BW, MOV_BTNS_MODE_SR_SL_SP1_V_DW, MOV_BTNS_MODE_SR_SL_SP1_V_UP, MOV_BTNS_MODE_SR_SL_SP1_H_BW, MOV_BTNS_MODE_SR_SL_SP1_H_FW, MOV_BTNS_MODE_SR_SL_SP1_V_DW,
	MOV_BTNS_MODE_SR_SL_SP1_V_DW, MOV_BTNS_MODE_SR_SL_SP1_H_FW, MOV_BTNS_MODE_SR_SL_SP1_H_BW, MOV_BTNS_MODE_SR_SL_SP1_V_DW, MOV_BTNS_MODE_SR_SL_SP1_V_DW, MOV_BTNS_MODE_SR_SL_SP1_H_BW, MOV_BTNS_MODE_SR_SL_SP1_H_FW, MOV_BTNS_MODE_SR_SL_SP1_V_DW,
	MOV_BTNS_MODE_SR_SL_SP1_V_DW, MOV_BTNS_MODE_SR_SL_SP1_H_BW, MOV_BTNS_MODE_SR_SL_SP1_H_FW, MOV_BTNS_MODE_SR_SL_SP1_V_UP, MOV_BTNS_MODE_SR_SL_SP1_V_DW, MOV_BTNS_MODE_SR_SL_SP1_H_FW, MOV_BTNS_MODE_SR_SL_SP1_H_BW, MOV_BTNS_MODE_SR_SL_SP1_V_UP,

	MOV_BTNS_MODE_SR_SL_SP2_V_DW, MOV_BTNS_MODE_SR_SL_SP2_H_BW, MOV_BTNS_MODE_SR_SL_SP2_H_FW, MOV_BTNS_MODE_SR_SL_SP2_V_DW, MOV_BTNS_MODE_SR_SL_SP2_V_DW, MOV_BTNS_MODE_SR_SL_SP2_H_FW, MOV_BTNS_MODE_SR_SL_SP2_H_BW, MOV_BTNS_MODE_SR_SL_SP2_V_DW,
	MOV_BTNS_MODE_SR_SL_SP2_V_UP, MOV_BTNS_MODE_SR_SL_SP2_H_FW, MOV_BTNS_MODE_SR_SL_SP2_H_BW, MOV_BTNS_MODE_SR_SL_SP2_V_DW, MOV_BTNS_MODE_SR_SL_SP2_V_UP, MOV_BTNS_MODE_SR_SL_SP2_H_BW, MOV_BTNS_MODE_SR_SL_SP2_H_FW, MOV_BTNS_MODE_SR_SL_SP2_V_DW,
	MOV_BTNS_MODE_SR_SL_SP2_V_DW, MOV_BTNS_MODE_SR_SL_SP2_H_FW, MOV_BTNS_MODE_SR_SL_SP2_H_BW, MOV_BTNS_MODE_SR_SL_SP2_V_DW, MOV_BTNS_MODE_SR_SL_SP2_V_DW, MOV_BTNS_MODE_SR_SL_SP2_H_BW, MOV_BTNS_MODE_SR_SL_SP2_H_FW, MOV_BTNS_MODE_SR_SL_SP2_V_DW,
	MOV_BTNS_MODE_SR_SL_SP2_V_DW, MOV_BTNS_MODE_SR_SL_SP2_H_BW, MOV_BTNS_MODE_SR_SL_SP2_H_FW, MOV_BTNS_MODE_SR_SL_SP2_V_UP, MOV_BTNS_MODE_SR_SL_SP2_V_DW, MOV_BTNS_MODE_SR_SL_SP2_H_FW, MOV_BTNS_MODE_SR_SL_SP2_H_BW, MOV_BTNS_MODE_SR_SL_SP2_V_UP,

	MOV_BTNS_MODE_SR_SL_SP3_V_DW, MOV_BTNS_MODE_SR_SL_SP3_H_BW, MOV_BTNS_MODE_SR_SL_SP3_H_FW, MOV_BTNS_MODE_SR_SL_SP3_V_DW, MOV_BTNS_MODE_SR_SL_SP3_V_DW, MOV_BTNS_MODE_SR_SL_SP3_H_FW, MOV_BTNS_MODE_SR_SL_SP3_H_BW, MOV_BTNS_MODE_SR_SL_SP3_V_DW,
	MOV_BTNS_MODE_SR_SL_SP3_V_UP, MOV_BTNS_MODE_SR_SL_SP3_H_FW, MOV_BTNS_MODE_SR_SL_SP3_H_BW, MOV_BTNS_MODE_SR_SL_SP3_V_DW, MOV_BTNS_MODE_SR_SL_SP3_V_UP, MOV_BTNS_MODE_SR_SL_SP3_H_BW, MOV_BTNS_MODE_SR_SL_SP3_H_FW, MOV_BTNS_MODE_SR_SL_SP3_V_DW,
	MOV_BTNS_MODE_SR_SL_SP3_V_DW, MOV_BTNS_MODE_SR_SL_SP3_H_FW, MOV_BTNS_MODE_SR_SL_SP3_H_BW, MOV_BTNS_MODE_SR_SL_SP3_V_DW, MOV_BTNS_MODE_SR_SL_SP3_V_DW, MOV_BTNS_MODE_SR_SL_SP3_H_BW, MOV_BTNS_MODE_SR_SL_SP3_H_FW, MOV_BTNS_MODE_SR_SL_SP3_V_DW,
	MOV_BTNS_MODE_SR_SL_SP3_V_DW, MOV_BTNS_MODE_SR_SL_SP3_H_BW, MOV_BTNS_MODE_SR_SL_SP3_H_FW, MOV_BTNS_MODE_SR_SL_SP3_V_UP, MOV_BTNS_MODE_SR_SL_SP3_V_DW, MOV_BTNS_MODE_SR_SL_SP3_H_FW, MOV_BTNS_MODE_SR_SL_SP3_H_BW, MOV_BTNS_MODE_SR_SL_SP3_V_UP,
};
float movements_drive_pattern[32] = {
	MOV_DRIVE_V_DW, MOV_DRIVE_H_BW, MOV_DRIVE_H_BW, MOV_DRIVE_V_DW, MOV_DRIVE_V_DW, MOV_DRIVE_H_FW, MOV_DRIVE_H_FW, MOV_DRIVE_V_DW,
	MOV_DRIVE_V_UP, MOV_DRIVE_H_FW, MOV_DRIVE_H_FW, MOV_DRIVE_V_DW, MOV_DRIVE_V_UP, MOV_DRIVE_H_BW, MOV_DRIVE_H_BW, MOV_DRIVE_V_DW,
	MOV_DRIVE_V_DW, MOV_DRIVE_H_FW, MOV_DRIVE_H_FW, MOV_DRIVE_V_DW, MOV_DRIVE_V_DW, MOV_DRIVE_H_BW, MOV_DRIVE_H_BW, MOV_DRIVE_V_DW,
	MOV_DRIVE_V_DW, MOV_DRIVE_H_BW, MOV_DRIVE_H_BW, MOV_DRIVE_V_UP, MOV_DRIVE_V_DW, MOV_DRIVE_H_FW, MOV_DRIVE_H_FW, MOV_DRIVE_V_UP
};

float movements_special_tricks_swim[104] = {
	90, 73, 70, 90, 90, 87, 150, 60,
	90, 80, 70, 60, 90, 80, 150, 60,
	90, 0, 70, 60, 60, 80, 150, 60,
	90, 0, 70, 60, 90, 80, 150, 60,
	20, 0, 0, 150, 0, 150, 150, 130,

	0, 0, 20, 135, 15, 90, 150, 135,
	15, 0, 40, 150, 15, 110, 150, 150,
	0, 0, 60, 150, 15, 130, 150, 135,
	15, 0, 80, 150, 15, 150, 150, 150,
	0, 0, 60, 150, 0, 130, 150, 135,
	15, 0, 40, 135, 0, 110, 150, 150,
	0, 0, 20, 135, 0, 90, 150, 135,
	15, 0, 0, 135, 0, 70, 150, 150
};
float movements_special_tricks_workout[56] = {
	90, 73, 70, 90, 90, 87, 150, 60,
	90, 80, 70, 60, 90, 80, 150, 60,
	90, 0, 70, 60, 60, 80, 150, 60,
	90, 0, 70, 60, 90, 80, 150, 60,
	20, 0, 40, 60, 90, 110, 150, 130,

	20, 0, 40, 60, 90, 110, 150, 130,//Down
	20, 0, 40, 120, 30, 110, 150, 130//Up
};
float movements_special_tricks_hello[] = {//Length TBD
	90, 73, 70, 90, 90, 87, 150, 60,
	90, 80, 70, 60, 90, 80, 150, 60,
	90, 0, 70, 60, 60, 80, 150, 60,
	90, 0, 70, 60, 90, 80, 150, 60,
	20, 0, 0, 150, 0, 150, 150, 130,

	0, 0, 20, 135, 15, 90, 150, 135,
	15, 0, 40, 150, 15, 110, 150, 150,
	0, 0, 60, 150, 15, 130, 150, 135,
	15, 0, 80, 150, 15, 150, 150, 150,
	0, 0, 60, 150, 0, 130, 150, 135,
	15, 0, 40, 135, 0, 110, 150, 150,
	0, 0, 20, 135, 0, 90, 150, 135,
	15, 0, 0, 135, 0, 70, 150, 150
};

float movements_kick_pose[8] = {
	40, 50, 40, 60, 60, 50, 30, 60
};